### PR TITLE
[timeformat] convert to unix

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Comment by kiddac** [comment]
@AbuBaniaz why do you need to do this?
I have tested this component and it works whether windows or unix line endings?

**Comment by AbuBaniaz** [comment]
It causes issues during build process

**Comment by kiddac** [comment]
Is this necessary on all files, i.e python files, bash files or just like that example on text files

**Comment by AbuBaniaz** [comment]
Sorry for delayed response. Build process failed on that file. The person who was helping me advised that all the files should be in Unix EOL as it causes issues during building process.

Python, bash and text files should be in unix eol. You can still edit them on windows.

**Pull request merged**
